server {
    listen 80;
    server_name coffeeshop.elkassa.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name api.coffeeshop.elkassa.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name coffeeshop.elkassa.com;

    ssl_certificate /etc/letsencrypt/live/coffeeshop.elkassa.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coffeeshop.elkassa.com/privkey.pem;

    location / {
        proxy_pass http://localhost:3050;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name api.coffeeshop.elkassa.com;

    ssl_certificate /etc/letsencrypt/live/api.coffeeshop.elkassa.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.coffeeshop.elkassa.com/privkey.pem;

    client_max_body_size 10M;

    location / {
        proxy_pass http://localhost:3051;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
