export const tunisianData = {
  "Ariana": ["Ariana Ville", "Ettadhamen", "Kalâat el-Andalous", "La Soukra", "Mnihla", "Raoued", "Sidi Thabet"],
  "Béja": ["Béja Nord", "Béja Sud", "Amdoun", "Goubellat", "Medjez el-Bab", "Nefza", "Teboursouk", "Testour", "Thibar"],
  "Ben Arous": ["Ben Arous", "Bou Mhel el-Bassatine", "El Mourouj", "Ezzahra", "Fouchana", "Hammam Chott", "Hammam Lif", "Mohamedia", "Medina Jadida", "Mégrine", "Mornag", "Radès"],
  "Bizerte": ["Bizerte Nord", "Bizerte Sud", "Ghar El Melh", "Ghezala", "Joumine", "Mateur", "Menzel Bourguiba", "Menzel Jemil", "Ras Jebel", "Sejnane", "Tinja", "Utique", "Zarzouna"],
  "Gabès": ["Gabès Ville", "Gabès Ouest", "Gabès Sud", "Ghannouch", "Hamma", "Mareth", "Matmata", "Nouvelle Matmata", "Menzel el-Habib", "Metouia"],
  "Gafsa": ["Gafsa Nord", "Gafsa Sud", "Belkhir", "El Guettar", "El Ksar", "Mdhilla", "Metlaoui", "Moularès", "Redeyef", "Sened", "Sidi Aïch"],
  "Jendouba": ["Jendouba Ville", "Jendouba Nord", "Aïn Draham", "Balta-Bou Aouane", "Bou Salem", "Fernana", "Ghardimaou", "Oued Mliz", "Tabarka"],
  "Kairouan": ["Kairouan Nord", "Kairouan Sud", "Bou Hajla", "Chebika", "Echrarda", "Haffouz", "Hajeb El Ayoun", "Nasrallah", "Oueslatia", "Sbikha", "Sidi Bou Ali"],
  "Kasserine": ["Kasserine Nord", "Kasserine Sud", "Ezzouhour", "Fériana", "Foussana", "Haïdra", "Jedelienne", "Magel Bel Abbès", "Sbeïtla", "Sbiba", "Thala"],
  "Kebili": ["Kebili Nord", "Kebili Sud", "Douz Nord", "Douz Sud", "Faouar", "Souk Lahad"],
  "Kef": ["Le Kef Est", "Le Kef Ouest", "Dahmani", "Jérissa", "Kalâat Khasba", "Kalaat Senan", "Ksour", "Nebeur", "Sakiet Sidi Youssef", "Sers", "Tajerouine"],
  "Mahdia": ["Mahdia", "Bou Merdes", "Chebba", "Chorbane", "El Jem", "Essouassi", "Hebira", "Ksour Essef", "Melloulèche", "Ouled Chamekh", "Sidi Alouane"],
  "Manouba": ["Manouba", "Borj El Amri", "Djedeida", "Douar Hicher", "Mornaguia", "Oued Ellil", "Tebourba"],
  "Medenine": ["Médenine Nord", "Médenine Sud", "Ajim", "Ben Guerdane", "Beni Khedache", "Houmt Souk", "Midoun", "Sidi Makhlouf", "Zarzis"],
  "Monastir": ["Monastir", "Bekalta", "Béni Hassen", "Jemmal", "Ksar Hellal", "Ksibet el-Médiouni", "Moknine", "Ouerdanine", "Sahline", "Sayada-Lamta-Bou Hajar", "Téboulba", "Zéramdine"],
  "Nabeul": ["Nabeul", "Béni Khiar", "Béni Khalled", "Bou Argoub", "Dar Chaâbane el-Fehri", "El Haouaria", "El Mida", "Grombalia", "Hammamet", "Kélibia", "Korba", "Menzel Bouzelfa", "Menzel Temime", "Soliman", "Takelsa"],
  "Sfax": ["Sfax Ville", "Sfax Ouest", "Sfax Sud", "Agareb", "Bir Ali Ben Khalifa", "El Amra", "El Hencha", "Graïba", "Jebiniana", "Kerkennah", "Mahres", "Menzel Chaker", "Sakiet Eddaïer", "Sakiet Ezzit"],
  "Sidi Bouzid": ["Sidi Bouzid Est", "Sidi Bouzid Ouest", "Bir El Hafey", "Cebbala Ouled Asker", "Jilma", "Menzel Bouzaiane", "Mezzouna", "Ouled Haffouz", "Regueb", "Sidi Ali Ben Aoun"],
  "Siliana": ["Siliana Nord", "Siliana Sud", "Bargou", "Bou Arada", "Gaâfour", "Kesra", "Makthar", "Rouhia", "Sidi Bou Rouis"],
  "Sousse": ["Sousse Ville", "Sousse Jawhara", "Sousse Riadh", "Sousse Sidi Abdelhamid", "Akouda", "Bouficha", "Enfidha", "Hammam Sousse", "Kalaâ Kebira", "Kalaâ Seghira", "Kondar", "M'saken", "Sidi Bou Ali", "Sidi El Hani"],
  "Tataouine": ["Tataouine Nord", "Tataouine Sud", "Bir Lahmar", "Dehiba", "Ghomrassen", "Remada"],
  "Tozeur": ["Tozeur", "Degache", "Hazoua", "Nefta", "Tamaghza"],
  "Tunis": ["Tunis Ville", "Bab El Bhar", "Bab Souika", "Carthage", "Cité El Khadra", "Djebel Jelloud", "El Kabaria", "El Menzah", "El Omrane", "El Omrane supérieur", "El Ouardia", "Ettahrir", "Ezzouhour", "Hraïria", "La Goulette", "La Marsa", "Le Bardo", "Le Kram", "Médina", "Sidi El Béchir", "Sidi Hassine"],
  "Zaghouan": ["Zaghouan", "Bir Mcherga", "El Fahs", "Nadhour", "Saouaf", "Zriba"]
};
